### ISSUE TITLE
Null safety badge is not showing for 0.0.7

### ISSUE THREAD

**Issue by nipunasudha** [SekolahCode/flutter_cache#8]
I am not sure this is normal for a newly published update, but the Null safety badge is not showing in the 0.0.7 release, which was supposed to be a null safe version (#6)

![image](https://user-images.githubusercontent.com/17500323/110670386-58b19080-81f3-11eb-8dcf-5a2e7d2837bd.png)

**Comment by ashrafkamarudin** [comment]
Sorry :sweat_smile: , that was a mistake on my part. I've re-published it to `v0.1.0` as advised by dart pub.
![image](https://user-images.githubusercontent.com/17607392/110745195-dd44f300-8275-11eb-961e-40cb1967376d.png)
